### ISSUE TITLE
Examples not working in 0.6

### ISSUE THREAD

**Issue by gcoda** [appleboy/drone-telegram#37]
As of drone 0.6 example in `DOCS.md` not working.
Spent some time to figure this out, works:
```
  telegram:
    image: appleboy/drone-telegram
    secrets: 
      - source: telegram_token
        target: plugin_token
    to: 12345679
    message: |
      Hello world
```

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@gcoda You should try:

```
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token ]
    to: 12345679
    message: |
      Hello world
```
