### ISSUE TITLE
Initialize New Bot Error: Not Found

### ISSUE THREAD

**Issue by Cysioland** [appleboy/drone-telegram#45]

**Comment by appleboy** [comment]
what is your drone config?

**Comment by Cysioland** [comment]
````YAML
pipeline:
  telegram:
    image: appleboy/drone-telegram
    token: $TELEGRAM_TOKEN
    to: $TELEGRAM_TO
    secrets: ['telegram_token', 'telegram_to']
````
