### ISSUE TITLE
Doesn't notify on failure

### ISSUE THREAD

**Issue by Cysioland** [appleboy/drone-telegram#49]
My `.drone.yml` part where this plugin is configured:
````YAML
pipeline:
  telegram:
    image: appleboy/drone-telegram
    pull: true
    secrets: [telegram_token, telegram_to]
    when:
      status: [success, failure]
````

**Comment by appleboy** [comment]
only receive the success message?

**Comment by Cysioland** [comment]
Yup, I only receive a message when build succeeds, none, when it fails, though I see "telegram" step being executed.

**Comment by ekeih** [comment]
FYI: The following configuration works (for me).

```
pipeline:
  test:
    image: alpine
    commands:
      - exit 1
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]
```
