### ISSUE TITLE
support loading token from secrets

### ISSUE THREAD

**Issue by changwuf31** [appleboy/drone-telegram#56]
Right now, I cannot load telegram token from secrets, unlike with kubernetes plugin where I can do things like:

```yaml
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: abc
    container: abc
    repo: gcr.io/xyz/abc
    tag: [ "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}" ]
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
```

doing it with this plugin

```yaml
  notify:
    image: appleboy/drone-telegram
    to: xxxxx
    format: markdown
    secrets: 
      - source: telegram_token
        target: token
```

results in 
> missing telegram token or user list

**Comment by appleboy** [comment]
TELEGRAM_TOKEN
TELEGRAM_TO

```yml
  notify:
    image: appleboy/drone-telegram
    to: xxxxx
    format: markdown
    secrets: 
      - source: your_telegram_token_variable
        target: telegram_token
```
