### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Lerentis** [appleboy/drone-telegram#57]
Hey there
Thanks for this plugin! it is awsome for private projects with a not so big infrastructure to back things up :D
I wanted to build a arch package on my server with drone and send it to me via telegram, but the documents are not send, there is just the error 
```
2018/02/23 22:19:15 invalid character '<' looking for beginning of value
```
my drone.yml is like this

```
pipeline:
  build:
    image: lerentis/build:arch
    commands:
      - "pacman -S --needed base-devel git wget yajl glibc glib2 icu libbsd libedit libutil-linux libxml2 ncurses python2 sqlite cmake ninja perl python2-requests python2-six python2-sphinx rsync swig clang --noconfirm"
      - "git clone https://aur.archlinux.org/libblocksruntime.git"
      - "chown -R nobody: libblocksruntime"
      - "chmod -R g+ws libblocksruntime"
      - "cd libblocksruntime" 
      - "sudo -u nobody makepkg"
      - "pacman -U libblocksruntime-0.4.1-1-x86_64.pkg.tar.xz --noconfirm && cd .."
      - "git clone https://aur.archlinux.org/swift-language.git"
      - "chown -R nobody: swift-language"
      - "chmod -R g+ws swift-language"
      - "cd swift-language && sudo -u nobody makepkg"
      - "ls -alh"
      - "pwd"
      - "mv swift-4.0.3-2-x86_64.pkg.tar.xz ../"
      - "mv swift-lldb-4.0.3-2-x86_64.pkg.tar.xz ../"
    cpu_quota: 0.80
    when:
      event: [ push, pull_request ]

  telegram:
    image: appleboy/drone-telegram
    token: masked
    to: masked
    document:
      - swift-4.0.3-2-x86_64.pkg.tar.xz
      - swift-lldb-4.0.3-2-x86_64.pkg.tar.xz
```

is there any issue with adding archives with this plugin? I have tested to just send empty files with the same name like this `echo test > swift-4.0.3-2-x86_64.pkg.tar.xz` which sends the file, so i think it is not the name of the file.

Any help or hint in the right direction would be greatly appreciated
