### ISSUE TITLE
HTML format reports "Bad Request: can't parse entities: Unsupported start tag"

### ISSUE THREAD

**Issue by hashworks** [appleboy/drone-telegram#64]
```
pipeline:
  telegram:
    image: appleboy/drone-telegram
    pull: true
    format: html
    secrets: [telegram_to, telegram_token]
```

results in:
```
2018/09/26 15:42:35 Bad Request: can't parse entities: Unsupported start tag "https://drone.git.example.com/example/example/25" at byte offset 10
```

**Comment by RecNes** [comment]
I'm facing with similar problem

```css
steps:
  notify-start:
    name: Send Build Start Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_USERID
      format: html
      message: |
        👷‍♂️ <b>Woodpecker Builder</b>
        
        <code>${CI_REPO_NAME}/${CI_COMMIT_BRANCH}</code> - Started <b>#${CI_PIPELINE_NUMBER}</b>
        👤 Commit Author: <i>${CI_COMMIT_AUTHOR}</i>
        
        📖 Commit Message: ${CI_COMMIT_MESSAGE}
        
        <a href='${CI_PIPELINE_URL}'>🔗 Details</a>
``` 

The configuration above throws this error when rendering the line containing `CI_COMMIT_MESSAGE` :
`2026/06/30 19:13:32 Bad Request: can't parse entities: Unsupported start tag "user@example.com" at byte offset 179`
Because of the commit message has < and > characters (see below). 


If I switch to markdown formatting, I'm seeing the new line characters of the `CI_COMMIT_MESSAGE`  as "\n" string.
`"Update telegram message\n\nSigned-off-by: User Name <user@example.com>\n"`
Can't find a way to make "\n" characters displayed properly in telegram.

The requirements are:
When using MARKDOWN format, "\n" character must be rendered properly.
When using HTML format, the "<" and ">" characters must be escaped properly.
