### ISSUE TITLE
send pdf to telegram group

### ISSUE THREAD

**Issue by volker-raschek** [appleboy/drone-telegram#66]
Hello, 
I want to use the telegram plugin to send a pdf document to a telegram group.

I defined this configuration into my `.drone.yml` file

```yaml
pipeline:
  telegram:
    image: appleboy/drone-telegram
    token: [ telegram_token ]
    to: [ telegram_user_id ]
    document:
      - index.pdf
    when:
      event: tag
    message: >
     {{#success build.status}}
       Build {{build.number}} succeeded for tag {{build.tag}}. Good job :)
     {{else}}
       Build {{build.number}} failed for tag {{build.tag}}. Fix me please :(
     {{/success}}
```

The telegram_token and telegram_user_id is defined over the drone web interface for the project.
But I get every time the error

```bash
2018/12/04 14:38:26 Not Found
```

I can not find out what the plugin not find. The PDF-Document, the user-group or the telegram token.

The readme should also be completed by the plugin. Finally, I'm not sure if the token is meant inclusive prefix (bot) or exclusive. In addition, the documentation only speaks of a user_id. Is it even possible to send files to a group? If so, this should be documented. If not, how can I specify multiple user_ids to send the document to?
