### ISSUE TITLE
step in drone 1.0 gives yaml parse error 

### ISSUE THREAD

**Issue by whysthatso** [appleboy/drone-telegram#67]
I've been trying to adjust to the 1.0 syntax, here's the snippet:

```yaml
steps:
  - name: send notification to telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 123456970
      message: >
        {{#success build.status}}
          build {{build.link}}, triggerd by {{commit.link}} from {{commit.author}} succeeded. Good job.
        {{else}}
          build {{build.link}}, triggerd by {{commit.link}} from {{commit.author}} failed. Fix me please.
        {{/success}}
    when:
      status:
        - success
        - failure
```

the secret is saved on the drone server in the format:
123456789:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

upon running a build i receive the following error:

```
Parse error on line 2:
Expecting OpenEndBlock, got: 'EOF'

I cannot identify the meaning of OpenEndBlock in this context, could anybody point me to the possible syntax error in the config?
```
