### ISSUE TITLE
strip commit message

### ISSUE THREAD

**Issue by lesinigo** [appleboy/drone-telegram#76]
I'm using the current version (image id `e526ca0ec7f0`) with the default template and I get all messages in Telegram with a newline between the commit and the closing 』 character.

I'm not a Go guy but as far as I can understand the plugin is getting the `Commit.Message` string with a trailing newline. I propose to strip that string of all leading and trailing blanks (spaces, tabs, newlines) before passing it to the template rendering.

This is a sample message in Telegram:
<img width="512" alt="Schermata 2019-03-19 alle 17 54 16" src="https://user-images.githubusercontent.com/6414339/54625843-52f39b00-4a70-11e9-962f-e5f1d226e00d.png">

This is the config I am using:
```yaml
- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token: <MY_TELEGRAM_TOKEN>
    to: <MY_TELEGRAM_ID>
  when:
    status: [ success, failure ]
```

I'm not too sure but this could be similar or related to issue #61 - actually if it was me I'd strip all incoming strings (commit message, author name, etc...)
