### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by masircana** [appleboy/drone-telegram#77]
I'm using the last version of the image with this format on my pipeline.
```
- name: notify
   image: appleboy/drone-telegram:1.3.1
   settings:
     format: markdown
     message: "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.     message}} ```\n\n🌐 {{ build.link }} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.  message}} ```\n\n🌐 {{ build.link }} {{/success}}\n"
     to:
       from_secret: TELEGRAM_TO
     token:
       from_secret: TELEGRAM_TOKEN
   when:
     status:
     - success
     - changed
     - failure
```
But im getting this error in all my pipelines. I see there is an update two hours ago on DockerHub. Maybe it's something broken or I have to change someting. 

![image](https://user-images.githubusercontent.com/55719678/65618828-93365780-df84-11e9-8900-97c2c7401e93.png)
