### ISSUE TITLE
Drone environment variables in bot message

### ISSUE THREAD

**Issue by suchimauz** [appleboy/drone-telegram#88]
Hello guys, how i use environment variables in bot message? 

Example, i want to show in message by error build at what steps is fails. Drone have environment, called - DRONE_FAILED_STEPS. How i use this ENV and other ENV`S on this plugin message part?

Or maybe your know other ways to output to a message failed steps?

Thanks is advance!

**Comment by e-zhydzetski** [comment]
Hello, @suchimauz!
Try to use *template_vars*:
```
  - name: notify
    image: appleboy/drone-telegram
    settings:
      template_vars:
        steps: ${DRONE_FAILED_STEPS}
      message: >
        Steps: {{tpl.steps}}
```
