### ISSUE TITLE
Kubernetes: build.status is always success

### ISSUE THREAD

**Issue by smnbbrv** [appleboy/drone-telegram#90]
Hi,

using your plugin for a long time. Thank you for your work!

However, on a new cluster I have a weird behaviour - regardless of the build result the status is always "success". Here is the config:

```yml
kind: pipeline
type: kubernetes
name: default

steps:
  - name: failure
    image: alpine
    commands:
      - exit 1
  
  - name: telegram
    when:
      status: [success, failure]
    image: appleboy/drone-telegram
    settings:
      debug: true
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      format: markdown
      message: |
        Build status: {{build.status}}

        {{#success build.status}}🚀{{else}}🐞{{/success}} {{repo.name}}@{{commit.branch}}

        {{commit.message}}
        More at {{build.link}}

        ----------
```

Here is how it runs

![image](https://user-images.githubusercontent.com/13453858/81291816-d0aaa980-906a-11ea-8402-88edf4bd74d3.png)

And here is the Telegram message:

![image](https://user-images.githubusercontent.com/13453858/81291861-e15b1f80-906a-11ea-8833-1697d09046a1.png)

I tried to put `debug: true` however it does not give any info concerning that issue.
